[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["UR5-coppelia"]

[project]
name = "UR5-coppelia"
version = "0.0.1"
dependencies = [
    "gymnasium",
    "coppeliasim_zmqremoteapi_client",
    "numpy",
]
